name             'oc-graphite'
maintainer       'Paul Mooring'
maintainer_email 'paul@getchef.com'
license          'All rights reserved'
description      'Installs and configures graphite'
version          '0.0.1'
